# Generated by Django 4.0.5 on 2023-03-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0010_alter_product_category_alter_reviews_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.CharField(choices=[('mb', 'mobile'), ('so', 'sofa'), ('ele', 'electronice'), ('Ts', 'T-Shirt'), ('by', 'Baby'), ('bg', 'Bags'), ('ft', 'Footwear'), ('jw', 'Jwellery'), ('be', 'Belt'), ('gif', 'Gift')], max_length=100),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='Category',
            field=models.CharField(choices=[('mb', 'mobile'), ('so', 'sofa'), ('ele', 'electronice'), ('Ts', 'T-Shirt'), ('by', 'Baby'), ('bg', 'Bags'), ('ft', 'Footwear'), ('jw', 'Jwellery'), ('be', 'Belt'), ('gif', 'Gift')], max_length=100),
        ),
    ]
